### PR TITLE
syntax highlight php snippets in README

### PR DESCRIPTION
**Pull request by fwolfst**

### CODE REVIEW

**Comment by ibes** [comment]
cool, thanks

**Comment by ibes** [comment]
@fwolfst not sure how to contact you otherwise:
Are you already an adopter of the plugin?
If so: Would be great to get in contact. 

The plugins was developed for one client and we intent to get it polished to be widely used. 
The current version mainly focussed on flexiblity and is rather developer centric. 
The idea is to get it a bit more user friendly - eg. offering two, three default layout options instead of: "just overwrite the theme to you liking". 

Would be great to collect use cases of others to be able to develop in a useful direction (which hopefully is both developer and user friendly - and for sure needs a more extended documentation)

**Comment by fwolfst** [comment]
> Are you already an adopter of the plugin?

@ibes No sorry, I just saw Felix Englishs ask for help in another channel, and while I am not in the position to help (really not enjoying PHP enough and general lack of resources) I thought I take a look and drive-by-commit.

> @fwolfst not sure how to contact you otherwise:

I will PM you to make a contact.

**Comment by fwolfst** [comment]
> > Are you already an adopter of the plugin?
> 
> @ibes No sorry, I just saw Felix Englischs ask for help in another channel, and while I am not in the position to help (really not enjoying PHP enough and general lack of resources) I thought I take a look and drive-by-commit.
> 
> > @fwolfst not sure how to contact you otherwise:
> 
> I will PM you to make a contact.

**Pull request merged**
